# the test suite runs the tests (headless, server+client) for multiple Meteor releases
name: Test suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Javascript standard lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-24-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-24-

      - run: |
          npm ci
          npm run lint
          npm run lint:ts
